### ISSUE TITLE
Unknown column 'rpp_subscription_transaction.name' in 'where clause'

### ISSUE THREAD

**Issue by manabroyown** [irsyadulibad/ci4-datatables#14]
PHP code 
      
 return DataTables::use('rpp_subscription_transaction')
            ->join('rpp_users', 'rpp_users.uid = rpp_subscription_transaction.user_id', 'INNER JOIN')					            
            ->addColumn('actions', function($data) {                
                return '<a href="'.base_url(route_to('s-admin-user-edit', $data->id)).'"><i class="fas fa-eye"></i></a>';
            })
            ->addColumn('transaction_status_col', function($data) {
                $class_active = $data->transaction_status == 'paid'?'badge-success':'badge-danger';                
                $transaction_status = ucwords($data->transaction_status);                
                return '<span class="badge '.$class_active.'">'.$transaction_status .'</span>';                
            })	         
            ->rawColumns(['actions', 'transaction_status_col'])   
	    ->make(true);

Javascript code

   $("#example1").DataTable({
      "processing": true,
      "serverSide": true,`
     "ajax": "<?=base_url(route_to('api-get-all-payments'))?>",
      "responsive": true, "lengthChange": false, "autoWidth": false,      
      "columns": [
        {data: 'name', name: 'name'},
        {data: 'date', name: 'Transaction Date'},
        {data: 'amount', name: 'Amount'},
        {data: 'period_start', name: 'Start'},
        {data: 'period_end', name: 'End'},       
        {data: 'transaction_status_col', name: 'Status', orderable: false },
        {data: 'actions', name: 'Actions', orderable: false }
      ],
      "searching": false,
    });

1. "name" column from 'rpp_users' table which is the secondary table.

**Comment by irsyadulibad** [comment]
You need alias if the name column is in the secondary table, this can be done via the select method
```php
->select('rpp_users.name as name')
```

**Comment by codepoetryindia** [comment]
> You need alias if the name column is in the secondary table, this can be done via the select method
> 
> ```
> ->select('rpp_users.name as name')
> ```

Thank you very much :)

**Comment by manabroyown** [comment]
Wow! It was a very BIG silly mistake :)

Thank you bro, Thank you very very much. You are awesome Bro.
