### ISSUE TITLE
Searching nggk jalan sempurna bang

### ISSUE THREAD

**Issue by emrafi** [irsyadulibad/ci4-datatables#2]
Data dengan value string/huruf nggk bisa di search bang, sama kalau mau nambah kolom nomer urut di pojok kiri gimana ya? 
![image](https://user-images.githubusercontent.com/33335254/100082148-717f7b80-2e7a-11eb-9862-fa9c2fcf48fa.png)
![image](https://user-images.githubusercontent.com/33335254/100082217-865c0f00-2e7a-11eb-9b6e-150fbd43229e.png)

makasih bang sebelumnya

**Comment by irsyadulibad** [comment]
Halo, mungkin bisa disertakan scriptnya?
setelah saya coba bisa dibuat search untuk angka maupun huruf dengan semestinya

![Capture](https://user-images.githubusercontent.com/47577443/100245769-fe096700-2f6a-11eb-9a3a-c4f9f7e1d84d.PNG)
![Capture](https://user-images.githubusercontent.com/47577443/100247116-8fc5a400-2f6c-11eb-87db-5f310a8424cc.PNG)


Untuk menambah kolom nomor, bisa pakai script berikut
```javascript
...
columns: [
    {data: null, sortable: false,
        render: function(data, type, row, meta){
            return meta.row + meta.settings._iDisplayStart + 1;
        )
    },
...
```

**Comment by emrafi** [comment]
ini jsnya bang
https://pastebin.com/zb62zL97
sama controllernya
https://pastebin.com/g1YKsWcK

makasih banyak bang

**Comment by emrafi** [comment]
![image](https://user-images.githubusercontent.com/33335254/100358205-6bc79880-3028-11eb-8820-877e4b9965b0.png)
sama itu, icon sort kenapa ya nggk mau diilangin bang, harus nge klik sort yang lain baru ilang

**Comment by putradongkal** [comment]
> ![image](https://user-images.githubusercontent.com/33335254/100358205-6bc79880-3028-11eb-8820-877e4b9965b0.png)
> sama itu, icon sort kenapa ya nggk mau diilangin bang, harus nge klik sort yang lain baru ilang

ini mah dari script jsnya, kalau ordernya ga di set maka order defaultnya ada di column 0

**Comment by putradongkal** [comment]
![image](https://user-images.githubusercontent.com/22538842/103473918-559fbb80-4dd0-11eb-9558-2ecb5368f54b.png)
Karena methodnya POST coba file di Library/[CI4 DATATABLE FOLDER]/src/utilities/Request.php baris 69 ganti `return $this->request->getGet($name);` jadi `return $this->request->getPost($name);`
![image](https://user-images.githubusercontent.com/22538842/103473944-b8915280-4dd0-11eb-96fd-14eb7a5f4845.png)

masalah ordering, filtering & searching saya solved setelah ubah ini.

**Comment by irsyadulibad** [comment]
> ![image](https://user-images.githubusercontent.com/22538842/103473918-559fbb80-4dd0-11eb-9558-2ecb5368f54b.png)
> Karena methodnya POST coba file di Library/[CI4 DATATABLE FOLDER]/src/utilities/Request.php baris 69 ganti `return $this->request->getGet($name);` jadi `return $this->request->getPost($name);`
> ![image](https://user-images.githubusercontent.com/22538842/103473944-b8915280-4dd0-11eb-96fd-14eb7a5f4845.png)
> 
> masalah ordering, filtering & searching saya solved setelah ubah ini.

Saya sarankan untuk memakai GET saja pada routenya, dan versi terbaru library ini memang diperuntukkan mengatasi hal tersebut. Karena jika proteksi CSRF diaktifkan secara auto generate akan terjadi error jika memakai POST. Ini terjadi pada versi sebelumnya

**Comment by emrafi** [comment]
ditempat saya nggk ada file itu bang

**Comment by emrafi** [comment]
> > ![image](https://user-images.githubusercontent.com/33335254/100358205-6bc79880-3028-11eb-8820-877e4b9965b0.png)
> > sama itu, icon sort kenapa ya nggk mau diilangin bang, harus nge klik sort yang lain baru ilang
> 
> ini mah dari script jsnya, kalau ordernya ga di set maka order defaultnya ada di column 0

![image](https://user-images.githubusercontent.com/33335254/103868280-4768dc80-50fb-11eb-9392-8cd003d8f4e0.png)

sudah saya tambahkan itu bang, tetep nggk mau ilang icon orderingnya

**Comment by destroylord** [comment]
Terima kasih banyak codenya sangat membantu sekali dan semoga rejekinya lancar dan diberikan kesehatan dan keselamatan

どうもありがとうございます
