### ISSUE TITLE
tabel with underscore not working

### ISSUE THREAD

**Issue by dira30** [irsyadulibad/ci4-datatables#6]
saya coba get tabel dengan undescore selalu gagal
misal nama table : user_students
mohon pencerahannya

**Comment by irsyadulibad** [comment]
Halo, bisa disertakan pesan errornya? Atau kode pada controller dan javascript.
Saya telah mencobanya pada project lokal dan bekerja dengan baik tanpa error.

Terima kasih

**Comment by dira30** [comment]
Maaf ternyata bukan masalah underscore tetapi join nya tdk jalan. padahal saya coba get data dari tabel pakai query bawaan bisa tp kenapa ya ketika menggunakan library ini tdk muncul data nya
![2021-01-22_16-10-15](https://user-images.githubusercontent.com/40995481/105470919-bc780c80-5ccc-11eb-83bf-06eb058e71e6.jpg)
?

**Comment by irsyadulibad** [comment]
Saya sudah memperbaikinya, masalah terletak pada query yang terlewatkan karena nama - nama kolom pada table yang dijoin tidak terdaftar.
Anda dapat melakukan update library dengan menjalankan perintah
```
composer update irsyadulibad/codeigniter4-datatables
```
Atau jika tidak menggunakan komposer, anda dapat mengunduh repository dan me replace seluruh file library.

Terima kasih
