### ISSUE TITLE
Search nya ga jalan

### ISSUE THREAD

**Issue by bastomiadi** [irsyadulibad/ci4-datatables#9]
Kalau kita search data yg kebetulan didalam tabel join maka kosong alias ga ketemu. Kalau di tabel utama datanya bisa ketemu.

**Comment by irsyadulibad** [comment]
Saya sudah memperbaikinya, masalah terletak pada query yang terlewatkan karena nama - nama kolom pada table yang dijoin tidak terdaftar.
Anda dapat melakukan update library dengan menjalankan perintah

composer update irsyadulibad/codeigniter4-datatables
Atau jika tidak menggunakan komposer, anda dapat mengunduh repository dan me replace seluruh file library.

Terima kasih

**Comment by bastomiadi** [comment]
Datanya jadi 0 records kalau ada data ribuan mas. Coba di cek. Di saya jadi ilang ga tampil datanya. Ini saya tes ada 2500 records di database nya tp gak mau muncul.

**Comment by irsyadulibad** [comment]
Halo, maaf untuk keterlambatan responnya
Saya telah mencoba dengan 5000 data dan tidak terdapat kendala sedikitpun.
![_20210314_151439](https://user-images.githubusercontent.com/47577443/111061918-4deb4a00-84d8-11eb-9cbb-769f8485d06c.jpg)
Mungkin anda bisa melakukan pengecekan pada server yang dipakai barangkali masalah tersebut muncul dikarenakan error pada sisi server.
